apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: call-centre-demo
  namespace: project-call-centre
spec:
  dnsNames:
  - '*.dashboard.callcentre.betalab.rp.bt.com'
  - '*.digitaltwin.callcentre.betalab.rp.bt.com'
  issuerRef:
    kind: ClusterIssuer
    name: betalab-le-production-issuer
  secretName: call-centre-demo-tls