{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "userinterface.serviceAccountName" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "userinterface.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "userinterface.serviceAccountName" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}