{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "userinterface.serviceAccountName" . }}-role
  labels:
    {{- include "userinterface.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - create
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments/status
  verbs:
  - get
{{- end }}
