adminservice:
  app:
    callReportingURL: http://dashboard-dashboardservice.istio-system.svc.cluster.local/api/v1/report
    myReportingURL: http://digitaltwin-adminservice.istio-system.svc.cluster.local/api/v1/report
    myReportingUser: worker
    myReportingPassword: w0rk3rP4ssW0rd
    workerImage: registry.docker.nat.bt.com/betalab-callcentre-digitaltwin/callcentre-digitaltwin-worker:105e33660e67a967099dfe837c54925213ff9cc2
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio
    hosts:
      - host: admin-service.digitaltwin.callcentre.panoptes.betalab.rp.bt.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: admin-digital-twin-cert
        hosts:
          - admin-service.digitaltwin.callcentre.panoptes.betalab.rp.bt.com

userinterface:
  app:
    auth:
      providerUrl: https://keycloak.auth.betalab.rp.bt.com/auth/realms
      tenantId: master
      clientId: callcentre-admin-ui
      lib: OIDC
    gatewayUrl: https://admin-service.digitaltwin.callcentre.panoptes.betalab.rp.bt.com/api/v1
    name: "Call Centre Admin Panel"
    hamburgerMenu: "no"
  
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: istio    
    hosts:
      - host: ui.digitaltwin.callcentre.panoptes.betalab.rp.bt.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ui-digital-twin-cert
        hosts:
          - ui.digitaltwin.callcentre.panoptes.betalab.rp.bt.com