adminservice:
  app:
    app:
      callReportingURL: https://dashboard-service.dashboard.callcentre.betalab.rp.bt.com/report
      myReportingURL: https://admin-service.digitalswin.callcentre.betalab.rp.bt.com/report
      workerImage: registry.docker.nat.bt.com/betalab-callcentre-digitaltwin/callcentre-digitaltwin-worker:8c35caf23a7cc0783920c56f251c50bd78b5b55b

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-production
    hosts:
      - host: admin-service.digitalswin.callcentre.betalab.rp.bt.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: call-centre-demo-tls
        hosts:
          - '*.dashboard.callcentre.betalab.rp.bt.com'
          - '*.digitaltwin.callcentre.betalab.rp.bt.com'