adminservice:
  app:
    callReportingURL: https://dashboard-service.dashboard.callcentre.betalab.rp.bt.com/api/v1/report
    myReportingURL: https://admin-service.digitaltwin.callcentre.betalab.rp.bt.com/api/v1/report
    myReportingUser: worker
    myReportingPassword: w0rk3rP4ssW0rd
    workerImage: registry.docker.nat.bt.com/betalab-callcentre-digitaltwin/callcentre-digitaltwin-worker:98947954dff604af105f7336abd2ab3fbc36ecd3

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-production
    hosts:
      - host: admin-service.digitaltwin.callcentre.betalab.rp.bt.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: call-centre-demo-tls
        hosts:
          - '*.dashboard.callcentre.betalab.rp.bt.com'
          - '*.digitaltwin.callcentre.betalab.rp.bt.com'
